### ISSUE TITLE
Promise in nodejs 0.10

### ISSUE THREAD

**Issue by ghost** [iamstarkov/npm-profile-downloads#2]
Native promise in this module not work in 0.10.
And tests pass in 0.10 only because they start in `babel-node`.

**Comment by iamstarkov** [comment]
okay, i see. i guess we can work that around with pinkie-promise

**Comment by iamstarkov** [comment]
https://github.com/floatdrop/pinkie-promise

**Comment by ghost** [comment]
I can attach fix to PR #1

**Comment by iamstarkov** [comment]
it will be cool
